name: Deployment

on: deployment

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Build application
        run: |
          echo 'build application'

  production:
    needs: [build]
    runs-on: ubuntu-latest
    environment:
      name: production
      url: https://example.com
    if: github.event.deployment.environment == 'production'
    steps:
      - name: Maintenance on
        if: github.event.deployment.task == 'maintenance'
        run: |
          echo 'Mainteannce on'
      - name: Prodcution deploy
        run: |
          echo ${{ github.event.deployment.environment }}

  staging:
    needs: [build]
    runs-on: ubuntu-latest
    environment:
      name: staging
      url: https://example.com
    if: github.event.deployment.environment == 'staging'
    steps:
      - name: Staging deploy
        run: |
          echo ${{ github.event.deployment.environment }}

  dev:
    needs: [build]
    runs-on: ubuntu-latest
    environment:
      name: dev
      url: https://example.com
    if: github.event.deployment.environment == 'dev'
    steps:
      - name: Dev deploy
        run: |
          echo ${{ github.event.deployment.environment }}

  maintenance-off:
    needs: [production]
    runs-on: ubuntu-latest
    environment:
      name: production
      url: https://example.com
    if: github.event.deployment.task == 'maintenance'
    steps:
      - name: Meintenance off
        run: |
          echo 'meintenance off'

  update-final-deploy-status-for-dev:
    needs: [dev, staging]
    runs-on: ubuntu-latest
    steps:
      - name: Set deployment status
        uses: rsotnychenko/deployment-status-update@0.2.0
        with:
          status: ${{ job.status }}
          run_id: ${{ github.run_id }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  update-final-deploy-status:
    needs: [production]
    runs-on: ubuntu-latest
    if: always()
    steps:
      - name: Set deployment status
        uses: rsotnychenko/deployment-status-update@0.2.0
        with:
          status: ${{ job.status }}
          run_id: ${{ github.run_id }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
